# Use H2 in-memory database
spring:
  datasource:
    url: jdbc:h2:mem:carRentalDb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop

sql:
  init:
    mode: always