spring:
  application:
    name: CarRentals
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
