name: Maven Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  API_CLIENT_TOKEN: ${{ secrets.API_CLIENT_PAT }}
  SHARED_ARTIFACTS_TOKEN: ${{ secrets.SHARED_ARTIFACT_SECRET }}
  TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}

jobs:
  unit-test:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up maven settings.xml
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [
              {
                "id": "github-api-client",
                "username": "${{ github.actor }}",
                "password": "${{ env.API_CLIENT_TOKEN }}"
              },
              {
                "id": "github-shared-artifacts",
                "username": "${{ github.actor }}",
                "password": "${{ env.SHARED_ARTIFACTS_TOKEN }}"
              }
            ]

      - name: Build & Run Tests
        run: mvn clean verify --fail-at-end

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: packaged-app
          path: target/*.jar