name: Maven Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      API_CLIENT_TOKEN: ${{ secrets.API_CLIENT_PAT }}
      SHARED_ARTIFACTS_TOKEN: ${{ secrets.SHARED_ARTIFACT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          settings-path: ${{ github.workspace }}

      - name: Set up maven settings.xml
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [
              {
                "id": "github-api-client",
                "username": "${{ github.actor }}",
                "password": "${{ env.API_CLIENT_TOKEN }}"
              },
              {
                "id": "github-shared-artifacts",
                "username": "${{ github.actor }}",
                "password": "${{ env.SHARED_ARTIFACTS_TOKEN }}"
              }
            ]

      - name: Build Project
        run: mvn clean package --fail-at-end

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: packaged-app
          path: target/*.jar

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4.2.1
        with:
          name: packaged-app
          path: target

      - name: Run Unit Tests
        run: mvn test --fail-at-end

      - name: Run Integration Tests
        run: mvn verify --fail-at-end -Pintegration-tests